#!/usr/bin/env python3

import os
import yaml
import argparse

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(dest='operation', help='Available operations')

add_parser = subparsers.add_parser('build', help='build script from omidocker file')
add_parser.add_argument('-f',"--file",dest="file_path", type=str, help='file path of omidocker.yml')

subtract_parser = subparsers.add_parser('status', help='get servcie status')
subtract_parser.add_argument('service_name', type=str, help='your service name')

subtract_parser = subparsers.add_parser('start', help='start, stoped service')
subtract_parser.add_argument('service_name', type=str, help='your service name')

subtract_parser = subparsers.add_parser('stop', help='stop service')
subtract_parser.add_argument('service_name', type=str, help='your service name')

args = parser.parse_args()


def create_service(service_name:str, service_desc:str, workdir = "/", command="", restart=False):
    data = f'''
[Unit]
Description={service_name} - {service_desc}

[Service]
User=root
WorkingDirectory={workdir}
ExecStart=/bin/bash -c '{command}'
{"Restart=always" if restart else ""}
{"RestartSec=3" if restart else ""}

[Install]
WantedBy=multi-user.target
'''
    open(f"/etc/systemd/system/{service_name}.service","w").write(data)

    return True


def restart_service(service_name:str):
    os.system(f"systemctl stop {service_name}.service")
    os.system(f"systemctl daemon-reload")
    os.system(f"systemctl start {service_name}.service")

    return os.system(f"systemctl status {service_name}")


def build(args):
    with open(args.get("file_path") if args.get("file_path") is not None else "./omidocker.yml", "r") as f:
        yaml_content = f.read()

    yaml_data = yaml.safe_load_all(yaml_content)
    data = list(yaml_data)[0]

    service_name = data.get("service_name")
    service_desc = data.get("service_desc", service_name)
    workdir = data.get("workdir", "./")
    command = data.get("command").replace("\n","\\")
    restart = data.get("restart", False)

    if (service_name == None) or (command == None):
        raise "service_name and command is required."
    
    create_service(
        service_name=service_name,
        service_desc=service_desc,
        workdir=workdir,
        command=command,
        restart=restart
    )

    status = restart_service(service_name=service_name)

    print(f"Service: {service_name}\nLocation: {workdir}\n Status:\n",status)


def start_service(name):
    return os.system(f"systemctl start {name}.service")


def status_service(name):
    return os.system(f"systemctl status {name}.service")


def stop_service(name):
    return os.system(f"systemctl stop {name}.service")


if __name__ == "__main__":
    args = args.__dict__

    print(args)

    if (args.get("operation") == "build"):
        build(args)
    elif (args.get("operation") == "start"):
        start_service(args.get("service_name"))
    elif (args.get("operation") == "status"):
        status_service(args.get("service_name"))
    elif (args.get("operation") == "stop"):
        stop_service(args.get("service_name"))

    
